# -*- coding: utf-8 -*-
from ckeditor.fields import RichTextField
from django.db import models

class OrderInfo(models.Model):
    order_id = models.AutoField(primary_key=True)
    order_sn = models.CharField(max_length=20)
    order_status = models.SmallIntegerField()
    shipping_status = models.SmallIntegerField()
    pay_status = models.SmallIntegerField()
    consignee = models.CharField(max_length=60)
    country = models.SmallIntegerField()
    province = models.SmallIntegerField()
    city = models.SmallIntegerField()
    district = models.SmallIntegerField()
    address = models.CharField(max_length=255)
    zipcode = models.CharField(max_length=60)
    tel = models.CharField(max_length=60)
    mobile = models.CharField(max_length=60)
    email = models.CharField(max_length=60)
    best_time = models.CharField(max_length=120)
    sign_building = models.CharField(max_length=120)
    postscript = models.CharField(max_length=255)
    shipping_id = models.SmallIntegerField()
    shipping_name = models.CharField(max_length=120)
    pay_id = models.SmallIntegerField()
    pay_name = models.CharField(max_length=120)
    how_oos = models.CharField(max_length=120)
    how_surplus = models.CharField(max_length=120)
    pack_name = models.CharField(max_length=120)
    card_name = models.CharField(max_length=120)
    card_message = models.CharField(max_length=255)
    inv_payee = models.CharField(max_length=120)
    goods_amount = models.DecimalField(max_digits=10,decimal_places=2)
    shipping_fee = models.DecimalField(max_digits=10,decimal_places=2)
    insure_fee = models.DecimalField(max_digits=10,decimal_places=2)
    pay_fee = models.DecimalField(max_digits=10,decimal_places=2)
    pack_fee = models.DecimalField(max_digits=10,decimal_places=2)
    card_fee = models.DecimalField(max_digits=10,decimal_places=2)
    money_paid = models.DecimalField(max_digits=10,decimal_places=2)
    surplus = models.DecimalField(max_digits=10,decimal_places=2)
    integral = models.IntegerField()
    integral_money = models.DecimalField(max_digits=10,decimal_places=2)
    bonus = models.DecimalField(max_digits=10,decimal_places=2)
    order_amount = models.DecimalField(max_digits=10,decimal_places=2)
    from_ad = models.SmallIntegerField()
    referer = models.CharField(max_length=255)
    add_time = models.IntegerField()
    confirm_time = models.IntegerField()
    pay_time = models.IntegerField()
    shipping_time = models.IntegerField()
    pack_id = models.SmallIntegerField()
    card_id = models.SmallIntegerField()
    bonus_id = models.IntegerField()
    invoice_no = models.CharField(max_length=255)
    extension_code = models.CharField(max_length=30)
    extension_id = models.IntegerField()
    to_buyer = models.CharField(max_length=255)
    pay_note = models.CharField(max_length=255)
    agency_id = models.SmallIntegerField()
    inv_type = models.CharField(max_length=60)
    tax = models.DecimalField(max_digits=10,decimal_places=2)
    is_separate = models.SmallIntegerField()
    parent_id = models.IntegerField()
    discount = models.DecimalField(max_digits=10,decimal_places=2)
    order_time_limit = models.IntegerField()
    kuaidi = models.IntegerField()
    kuaidi_result = RichTextField()
    is_lacode = models.SmallIntegerField()
    expires_time = models.IntegerField()
    order_sn_cappay =models.CharField(max_length=30)
    browse_type = models.SmallIntegerField()
    user_id = models.IntegerField()

    def __unicode__(self):
        return self.order_sn

    class Meta:
        db_table = 'shouji_order_info'
        verbose_name = u"订单"
